version: '3.8'

services:
  gis-siap-revamp-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis_siap_revamp_frontend_dev
    ports:
      - "81:80"
    networks:
      gisnet:
        aliases:
          - gis-siap-revamp-dev.docker
    restart: unless-stopped


networks:
  gisnet:
    external: true
